config/routes.rb
Rails.application.routes.draw do
  get 'profile/edit'
  post 'profile', to: 'profile#update'
  get 'user_files/new'
  get 'user_files/index'
  get 'user_files/attach/:id', to: 'user_files#attachment', as: :user_files_attachment
  get 'user_files/:id', to: 'user_files#show', as: :user_files_show
  post 'user_files', to: 'user_files#create'
  get 'user_files_export/new', to: 'user_files#export_new'
  post 'user_files_export', to: 'user_files#export_create'

  resources :file_adapters
  devise_for :users
  resources :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/user_files_controller.rb
class UserFilesController < ApplicationController

  def attachment
    #TODO: 権限
    @attach = KassisFileAttachment.find(params[:id])

    export_folder = Rails.application.config.kassis.export_folder
    export_folder = File.expand_path(export_folder, Rails.root)

    filepath = File.join(export_folder, @attach.filename)

    stat = File::stat(filepath)
    send_file(filepath, :filename => @attach.filename, :length => stat.size)
  end

  def export_new
    @message_adapter = MessageAdapter.new
  end

  def new
    @message_adapter = MessageAdapter.new
  end

  def create
    @message_adapter = MessageAdapter.new(message_adapter_params)

    rabbitmq_hostname = Rails.application.config.rabbitmq.host
    rabbitmq_quename = Rails.application.config.rabbitmq.quename
    connection = Bunny.new(hostname: rabbitmq_hostname)
    connection.start

    @message_adapter.msgid = SecureRandom.uuid
    @message_adapter.created_by = current_user.id
    @message_adapter.status = 'set' # set -> (accepted) -> processing -> processed
    @message_adapter.state = 'normal' # normal -> error or sucess
    @message_adapter.message_type = 'user.file.import'

    if @message_adapter.save

      attachment = @message_adapter.importfile
      dest_dir = File.join(
            Rails.root,
          "storage",
            attachment.blob.key.first(2),
            attachment.blob.key.first(4).last(2))
      filepath = File.join(dest_dir, @message_adapter.importfile.blob.key)

      message = ({msgid: @message_adapter.msgid,
                  message_type: @message_adapter.message_type,
                  filepath: filepath,
                  blob: @message_adapter.importfile.blob}).to_json

      channel = connection.create_channel
      queue = channel.queue(rabbitmq_quename)
      queue.publish(message, persistent: true)
      connection.close
      logger.info " [x] Sent Message q:#{rabbitmq_quename} m:#{message}"
      redirect_to user_files_show_path(@message_adapter.id), notice: 'Message adapter was successfully created.'
    else
      render :new
    end
  end

  def export_create
    @message_adapter = MessageAdapter.new(message_adapter_params)

    rabbitmq_hostname = Rails.application.config.rabbitmq.host
    rabbitmq_quename = Rails.application.config.rabbitmq.quename
    connection = Bunny.new(hostname: rabbitmq_hostname)
    connection.start

    export_folder = Rails.application.config.kassis.export_folder
    export_folder = File.expand_path(export_folder, Rails.root)

    @message_adapter.msgid = SecureRandom.uuid
    @message_adapter.created_by = current_user.id
    @message_adapter.status = 'set' # set -> (accepted) -> processing -> processed
    @message_adapter.state = 'normal' # normal -> error or sucess
    @message_adapter.message_type = 'user.file.export'

    if @message_adapter.save

      message = ({msgid: @message_adapter.msgid,
                  message_type: @message_adapter.message_type,
                  filepath: export_folder}).to_json

      channel = connection.create_channel
      queue = channel.queue(rabbitmq_quename)
      queue.publish(message, persistent: true)
      connection.close
      logger.info " [x] Sent Message q:#{rabbitmq_quename} m:#{message}"
      redirect_to user_files_show_path(@message_adapter.id), notice: 'Message adapter was successfully created.'
    else
      render :new
    end

  end


  def index
  end

  def show
    @message_adapter = MessageAdapter.find(params['id'])
    @message_histories = MessageHistory.where(msgid: @message_adapter.msgid)
    @message_attachments = KassisFileAttachment.where(msgid: @message_adapter.msgid)
  end

  private
  def message_adapter_params
    params.permit(:name, :importfile)
  end
end

app/helpers/user_files_helper.rb
module UserFilesHelper
end

app/views/user_files/export_new.html.erb
<script type="text/javascript">
function breadcrumbs() {
  $("#breadcrumbs").text("利用者情報出力")
}
breadcrumbs();
</script>

<div class="container-fluid">
<%= form_with url: user_files_export_path, local: true do |form| %>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/user_files/index.html.erb
<h1>UserFiles#index</h1>
<p>Find me in app/views/user_files/index.html.erb</p>

app/views/user_files/new.html.erb
<div class="container-fluid">
<%= form_with url: user_files_path, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :importfile %>
    <%= form.file_field :importfile %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/user_files/show.html.erb
<h1>UserFiles#show</h1>
<p>Find me in app/views/user_files/show.html.erb</p>

<div class="card" style="width: 20rem;">
  <div class="card-body">
    <p class="card-text" id="file_status"> </p>
  </div>
</div>

<%= @message_adapter.msgid %> <br />
<%= @message_adapter.message_type %> <br />
<%= @message_adapter.status %> <br />
<%= @message_adapter.state %> <br />
<%= @message_adapter.created_by %> <br />
<%= @message_adapter.created_at %> <br />

<hr />

<% @message_histories.each do |h| %>
  <%= h.message_type %>
  <%= h.status %>
  <%= h.note %>
  <%= h.updated_at %>
  <br />
<% end %>

<hr />

<% @message_attachments.each do |h| %>
  <%= h.msgid %> <br />
  <%= h.fileid %> <br />
  <%= h.filename %> <br />
  <%= h.byte_size %> <br />
  <%= h.checksum %> <br />
  <%= h.created_at %> <br />

  <%= link_to h.filename, user_files_attachment_path(h.id) %>

<% end %>