config/routes.rb
Rails.application.routes.draw do
  get 'profile/edit'
  post 'profile', to: 'profile#update'
  get 'user_files/new'
  get 'user_files/index'
  get 'user_files/attach/:id', to: 'user_files#attachment', as: :user_files_attachment
  get 'user_files/:id', to: 'user_files#show', as: :user_files_show
  post 'user_files', to: 'user_files#create'
  get 'user_files_export/new', to: 'user_files#export_new'
  post 'user_files_export', to: 'user_files#export_create'

  resources :file_adapters
  devise_for :users
  resources :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable  :registerable
  devise :ldap_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:username]

  include UserSearchable

  validates_uniqueness_of :username, :allow_nil => true, :allow_blank => true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }, :allow_nil => true, :allow_blank => true
  validate :some_id_is_blank

  before_save :setup_attr
  before_create :build_personid
  after_create_commit :create_ldap
  after_update_commit :update_ldap
  after_destroy_commit :destroy_ldap

  MIN_PASSWORD_LENGTH_ALLOWED = 8

  def valid_password?(params)
    # TODO: Rails実装のvalidationにする
    if params[:password].blank?
      errors[:base] << "パスワードが空です。"
      return false
    end
    if params[:password].size < MIN_PASSWORD_LENGTH_ALLOWED
      errors[:base] << "パスワードが短いです。８文字以上入力してください。"
      return false
    end
    if params[:password_confirmation].blank?
      errors[:base] << "パスワード(確認)が空です。"
      return false
    end

    unless params[:password] == params[:password_confirmation]
      errors[:base] << "パスワードと確認パスワードが一致しません"
      return false
    end

    true
  end

  def setup_attr
    self.email.strip! if self.email
    if self.email.blank?
      self.email = nil
    end

    self.password.strip! if self.password
    if self.password.blank?
      self.password = nil
    end

    # password
    if self.id.blank? && self.username.present? && self.password.blank?
      # 新規作成時(id空)でログインID(username)記入済みでパスワードが空の場合に自動生成する
      generated_password = Devise.friendly_token.first(8)
      puts "@@@ generated_password:#{generated_password}"
      self.password = generated_password
    end

  end

  def some_id_is_blank
    unless cardid.present? or email.present? or username.present? or full_name.present?
      errors.add(:cardid, "利用者番号、Eメールアドレス、ログインID、フルネーム　のいずれかを入力してください。")
    end
  end

  def build_personid
    self.personid = SecureRandom.uuid
  end

  def update_ldap

  end

  def update_ldap_password
    # TODO: もうちょっとうまい方法は無いのか。
    ldap_config = YAML.load(ERB.new(File.read(::Devise.ldap_config || "#{Rails.root}/config/ldap.yml")).result)[Rails.env]
    base_dn = ldap_config['base']
    # TODO: ログインＩＤに相当する項目は、ldap.ymlのattributeから取得する
    logger.info "@@1 update_ldap_password"
    dn = "uid=#{self.username}, #{base_dn}"
    attr = {
        :userPassword => self.password,
    }
    operation_result = nil
    auth = { :method => :simple,
             :username => ldap_config["admin_user"],
             :password => ldap_config["admin_password"]
    }
    Net::LDAP.open(:host => ldap_config["host"],
                   :port => ldap_config["port"],
                   :auth => auth) do |ldap|

      unless ldap.password_modify(dn: dn,
                                   auth: auth,
                                   new_password: self.password)

        operation_result = ldap.get_operation_result
      end
    end

    if operation_result
      unless operation_result.code == 0
        if operation_result.code == 68
          # Entry Already Exists
        end
        puts "LDAP error."
        pp operation_result
      end
    end

  end

  def destroy_ldap
    # TODO: もうちょっとうまい方法は無いのか。
    ldap_config = YAML.load(ERB.new(File.read(::Devise.ldap_config || "#{Rails.root}/config/ldap.yml")).result)[Rails.env]
    base_dn = ldap_config['base']
    # TODO: ログインＩＤに相当する項目は、ldap.ymlのattributeから取得する
    logger.info "@@1 destroy_ldap"
    dn = "uid=#{self.username}, #{base_dn}"

    operation_result = nil
    auth = { :method => :simple,
             :username => ldap_config["admin_user"],
             :password => ldap_config["admin_password"]
    }
    Net::LDAP.open(:host => ldap_config["host"],
                   :port => ldap_config["port"],
                   :auth => auth) do |ldap|

      unless ldap.delete(dn: dn)
        operation_result = ldap.get_operation_result
      end
    end

    if operation_result
      unless operation_result.code == 0
        if operation_result.code == 68
          # Entry Already Exists
        end
        puts "LDAP error."
        pp operation_result
      end
    end
  end

  # TODO: 別のコードにリファクタリング
  def create_ldap
    unless username.present?
      logger.info "username is blank. skip create ldap"
    end

    # TODO: もうちょっとうまい方法は無いのか。
    ldap_config = YAML.load(ERB.new(File.read(::Devise.ldap_config || "#{Rails.root}/config/ldap.yml")).result)[Rails.env]
    base_dn = ldap_config['base']
    # TODO: ログインＩＤに相当する項目は、ldap.ymlのattributeから取得する
    logger.info "@@1 ldap_before_save"
    dn = "uid=#{self.username}, #{base_dn}"
    attr = {
        :cn => "#{self.username}",
        :sn => "#{self.username}",
        :uid => self.username,
        :userPassword => self.password,
        :objectclass => ['inetOrgPerson'],
    }

    operation_result = nil
    auth = { :method => :simple,
             :username => ldap_config["admin_user"],
             :password => ldap_config["admin_password"]
    }
    Net::LDAP.open(:host => ldap_config["host"],
                   :port => ldap_config["port"],
                   :auth => auth) do |ldap|
      unless ldap.add(dn: dn, attributes: attr)
        operation_result = ldap.get_operation_result
      end
    end
    if operation_result
      unless operation_result.code == 0
        if operation_result.code == 68
          # Entry Already Exists
        end
        puts "LDAP error."
        pp operation_result
      end
    end
  end

  def ldap_before_save
    logger.info "@@1 ldap_before_save"
    #name = Devise::LDAP::Adapter.get_ldap_param(self.username, "cn")
    #self.name = name.first
    #self.email = self.name + "@foo.com"
    #self.time_zone = "Tokyo"
  end

  #usernameを利用してログインするようにオーバーライド
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      #認証の条件式を変更する
      where(conditions).where(["username = :value", { :value => username }]).first
    else
      where(conditions).first
    end
  end

  #登録時にemailを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json do
        query = '*'
        if params[:q].present?
          query = params[:q]
        end

        # TODO: 表示できる最大件数の定義をどこかでする
        response = User.search(query).page(1).per(5000)

        total_records = response.records.total
        users = response.results.map { |r| r._source }

        logger.info "total result: #{response.records.total}"

        render json: {records: users, total_records: total_records}
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    #random_password = SecureRandom.urlsafe_base64(7)
    #@user.password = random_password
    #logger.info("p=#{random_password}")

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :email, :personid, :cardid,
                                 :full_name, :full_name_transcription,
                                 :expired_at, :registration_date, :note, :deactive, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<script>
  document.addEventListener("DOMContentLoaded", function() {
      AutoKana.bind("#user_full_name", "#user_full_name_transcription", { katakana: true });
  });
</script>

<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cardid %>
    <%= form.text_field :cardid, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :full_name_transcription %>
    <%= form.text_field :full_name_transcription %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :expired_at %>
    <%= form.date_field :expired_at %>
  </div>

  <div class="field">
    <%= form.label :registration_date %>
    <%= form.date_field :registration_date %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="field">
    <%= form.label :deactive %>
    <%= form.check_box :deactive %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/edit.html.erb
<div class="container-fluid">
<h1>利用者情報の編集</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<script type="text/javascript">


    function breadcrumbs() {
        $("#breadcrumbs").text("利用者一覧")
    }
    function buildGrid(params) {
      var baseurl = "<%= users_path(:format => :json) %>";
      var url = baseurl + "?" + QueryString.stringify(params, null, null, true)
      $.ajax({
          type: 'GET',
          url: url,
          dataType: 'json'
      })
      // Ajaxリクエストが成功した時発動
      .done((results) => {
        var records = results.records;
        $("#grid_view").empty();
        // initialize
        const grid = new cheetahGrid.ListGrid({
          parentElement: document.querySelector('#grid_view'),
          // Header definition
          header: [
              {field: 'check', caption: '', width: 50, columnType: 'check', action: 'check',
                  headerStyle: {bgColor: '#ccc'}},
              {field: 'personid', caption: 'PersonID', width: 100, columnType: 'center',
                  style: {font: '11px sans-serif'},
                  headerStyle: {bgColor: '#ccc', color: 'black', font: '11px sans-serif'}},
              {field: 'full_name', caption: '氏名', width: 120,
                  style: {font: '11px sans-serif', padding: [3/*top*/, 5/*right*/, 3/*bottom*/, 8/*left*/]},
                  headerStyle: {bgColor: '#ccc', color: 'black', font: '11px sans-serif'}},
              {field: 'full_name_transcription', caption: '氏名ヨミ', width: 140,
                  style: {font: '11px sans-serif'},
                  headerStyle: {bgColor: '#ccc', color: 'black', font: '11px sans-serif'}},
              {field: 'username', caption: 'ログインID', width: 120,
                  style: {font: '11px sans-serif'},
                  headerStyle: {bgColor: '#ccc', color: 'black', font: '11px sans-serif'}},
              {field: 'cardid', caption: 'Card ID', width: 120,
                  style: {font: '11px sans-serif'},
                  headerStyle: {bgColor: '#ccc', color: 'black', font: '11px sans-serif'}},
              {field: 'show', width: 80,
                  columnType: new cheetahGrid.columns.type.ButtonColumn({
                      caption: '詳細',
                  }),
                  action: new cheetahGrid.columns.action.ButtonAction({
                      action(rec) {
                          window.location.href = '<%= polymorphic_url :users %>' + '/' + rec.user_id;
                      },
                  }),
                  headerStyle: {bgColor: '#ccc', color: 'black'},
              }
          ],
          defaultRowHeight: 24,
          headerRowHeight: 24,
          records,
          frozenColCount: 3,
        });
        grid_status.innerText = "" + records.length + " レコード / 全件 " + results.total_records + " レコード";
      })
      // Ajaxリクエストが失敗した時発動
      .fail((data) => {
        console.log('fail');
      });
    }

    $(document).ready(function(){
        breadcrumbs();
        buildGrid("");

      $('#submit_button').click(function(){
          var serialize = $('#user_search_form').serializeArray();
          var params = {};
          // 配列 -> 連想配列に
          for (idx in serialize) {
              var key   = serialize[idx]["name"];
              var value = serialize[idx]["value"];
              params[key] = value;
          }
          buildGrid(params);
          return false;
      });
    });

</script>

<div class="container-fluid">
  <div id="search-field" style="padding-bottom: 5px">

    <form id="user_search_form" action="/users" accept-charset="UTF-8" method="get">
      <input autosave="false" onsearch="true" incremental="true" type="search" name="q" id="user_search_form_q" />
      <button type="submit" id="submit_button">検索</button>
    </form>
  </div>

  <div id="grid_view" style="height: 400px; border: solid 1px #ddd;">
  </div>
  <div id="grid_status" style="height: 30px; background-color: #DDDDDD">
  </div>

  <%= link_to "利用者新規作成", new_user_path, {class: "btn btn-primary"} %>
  <%= link_to user_files_new_path, {class: "btn btn-primary"} do %>
    <i class="fas fa-upload"></i> ファイル取込
  <% end %>
  <%= link_to user_files_export_new_path, {class: "btn btn-primary"} do %>
    <i class="fas fa-download"></i> ファイル出力
  <% end %>

</div>

app/views/users/new.html.erb
<div class="container-fluid">
<h1>利用者情報の新規作成</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
<p id="notice"><%= notice %></p>

<p>
  <strong>CardID:</strong>
  <%= @user.cardid %>
</p>

<p>
  <strong>username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>full_name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>full_name_transcription:</strong>
  <%= @user.full_name_transcription %>
</p>

<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>expired_at:</strong>
  <%= @user.expired_at %>
</p>

<p>
  <strong>registration_date:</strong>
  <%= @user.registration_date %>
</p>

<p>
  <strong>deactive:</strong>
  <%= @user.deactive %>
</p>

<p>
  <strong>note:</strong>
  <%= @user.note %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

</div>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>