config/routes.rb
Rails.application.routes.draw do
  get 'profile/edit'
  post 'profile', to: 'profile#update'
  get 'user_files/new'
  get 'user_files/index'
  get 'user_files/attach/:id', to: 'user_files#attachment', as: :user_files_attachment
  get 'user_files/:id', to: 'user_files#show', as: :user_files_show
  post 'user_files', to: 'user_files#create'
  get 'user_files_export/new', to: 'user_files#export_new'
  post 'user_files_export', to: 'user_files#export_create'

  resources :file_adapters
  devise_for :users
  resources :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/file_adapter.rb
class FileAdapter < ApplicationRecord
  has_one_attached :importfile

  validates :importfile, presence: true
end

app/helpers/file_adapters_helper.rb
module FileAdaptersHelper
end

app/views/file_adapters/_form.html.erb
<%= form_with(model: file_adapter, local: true) do |form| %>
  <% if file_adapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(file_adapter.errors.count, "error") %> prohibited this file_adapter from being saved:</h2>

      <ul>
      <% file_adapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :created_by %>
    <%= form.number_field :created_by %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/file_adapters/edit.html.erb
<h1>Editing File Adapter</h1>

<%= render 'form', file_adapter: @file_adapter %>

<%= link_to 'Show', @file_adapter %> |
<%= link_to 'Back', file_adapters_path %>

app/views/file_adapters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>File Adapters</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Created by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_adapters.each do |file_adapter| %>
      <tr>
        <td><%= file_adapter.title %></td>
        <td><%= file_adapter.created_by %></td>
        <td><%= link_to 'Show', file_adapter %></td>
        <td><%= link_to 'Edit', edit_file_adapter_path(file_adapter) %></td>
        <td><%= link_to 'Destroy', file_adapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File Adapter', new_file_adapter_path %>

app/views/file_adapters/new.html.erb
<h1>New File Adapter</h1>

<%= render 'form', file_adapter: @file_adapter %>

<%= link_to 'Back', file_adapters_path %>

app/views/file_adapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @file_adapter.title %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @file_adapter.created_by %>
</p>

<%= link_to 'Edit', edit_file_adapter_path(@file_adapter) %> |
<%= link_to 'Back', file_adapters_path %>