config/routes.rb
Rails.application.routes.draw do
  get 'profile/edit'
  post 'profile', to: 'profile#update'
  get 'user_files/new'
  get 'user_files/index'
  get 'user_files/attach/:id', to: 'user_files#attachment', as: :user_files_attachment
  get 'user_files/:id', to: 'user_files#show', as: :user_files_show
  post 'user_files', to: 'user_files#create'
  get 'user_files_export/new', to: 'user_files#export_new'
  post 'user_files_export', to: 'user_files#export_create'

  resources :file_adapters
  devise_for :users
  resources :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>kassis soda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag() %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

  </head>

  <style>
    .navbar-brand {
      background: url("/images/logo.png") no-repeat left center;
      background-size: contain;
      height: 40px;
      width: 40px;
    }
  </style>

  <body>
    <% if user_signed_in? %>
    <nav class="navbar py-0 navbar-expand-lg navbar-light bg-secondary">
      <nav class="navbar">
        <a class="navbar-brand" href="<%= url_for root_path %>">
        </a>
      </nav>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto navbar-text" id="breadcrumbs">
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" accesskey="s">
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">検索</button>
        </form>

        <ul class="navbar-nav">
          <a href="#" class="btn btn-default">
            <span class="fa-stack fa-1x">
              <span class="fas fa-square fa-stack-2x" style="color:whitesmoke"></span>
              <strong class="fa-stack-1x" style="color:darkgray;">0</strong>
            </span>
          </a>
        </ul>

        <ul class="navbar-nav">
          <li class="nav-item dropdown dropleft">
            <button type="button" class="btn btn-outline-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              個人設定
            </button>
            <div class="dropdown-menu text-center" aria-labelledby="navbarDropdown">
              Signed in as <%= current_user.username %>
              <div class="dropdown-divider"></div>
              <%= link_to 'プロフィール', profile_edit_path, :class => 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
            </div>
          </li>
        </ul>

      </div>
    </nav>
    <% end %>

    <% if notice %>
    <p class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">close</span>
      </button>
      <%= notice %>
    </p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">close</span>
      </button>
      <%= alert %>
    </p>
  <% end %>

  <div class="container-fluid py-1">
    <%= yield %>
  </div>
  </body>
</html>